
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReviewZone.Db
{

using System;
    using System.Collections.Generic;
    
public partial class RoleType
{

    public int Role_ID { get; set; }

    public int User_ID { get; set; }

    public string Category { get; set; }



    public virtual AccountLogin AccountLogin { get; set; }

}

}
